# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Run clang-tidy

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/run-clang-tidy.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - ".clang-tidy"
      - "CMakeLists.txt"
      - "conanfile.txt"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/run-clang-tidy.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - ".clang-tidy"
      - "CMakeLists.txt"
      - "conanfile.txt"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONAN_HOME: '/root/.conan2'

jobs:
  run-clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-22.04-cxx-clang-15
      options: '--user=root'

    steps:
      - uses: actions/checkout@v3

      - name: Print clang-tidy version
        run: clang-tidy --version

      - name: Generate cache key
        id: cache-key
        run: |
          hash="${{ hashFiles('conanfile.txt', '.github/workflows/run-clang-tidy.yml') }}"

          echo "key=run-clang-tidy-$hash" >> $GITHUB_OUTPUT

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: conan-${{ steps.cache-key.outputs.key }}
          path: ${{ env.CONAN_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source
          conan remove --confirm "*"

      - name: Install build dependencies
        run: |
          conan install .                        \
             --build=missing                     \
             --build=cascade                     \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH" \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH" \
             -s build_type=Debug                 \
             -s compiler.libcxx=libstdc++11      \
             -s compiler.cppstd=17               \
             --output-folder=build

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug                      \
                -DCMAKE_PREFIX_PATH="$PWD/build"              \
                -DENABLE_DEVELOPER_MODE=ON                    \
                -DOPT_ENABLE_SANITIZER_ADDRESS=OFF            \
                -DOPT_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=OFF \
                -DOPT_ENABLE_CLANG_TIDY=ON                    \
                -DCOOLERPP_BUILD_EXAMPLES=ON                  \
                -DCOOLERPP_ENABLE_TESTING=ON                  \
                -S .                                          \
                -B build

      - name: Build project
        run: cmake --build build -j $(nproc)


  clang-tidy-status-check:
    name: Status Check (clang-tidy)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - run-clang-tidy

    steps:
      - name: Collect job results
        if: needs.run-clang-tidy.result != 'success'
        run: exit 1
