# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Unit tests Ubuntu

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/unit-tests-ubuntu.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/unit-tests-ubuntu.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  CONAN_V2_MODE: "1"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { image: conanio/gcc8,                build_type: Debug,   developer_mode: OFF }
          - { image: conanio/gcc12-ubuntu16.04,   build_type: Debug,   developer_mode: ON }
          - { image: conanio/gcc12-ubuntu16.04,   build_type: Release, developer_mode: OFF }
          - { image: conanio/clang8,              build_type: Debug,   developer_mode: OFF }
          - { image: conanio/clang14-ubuntu16.04, build_type: Debug,   developer_mode: ON }
          - { image: conanio/clang14-ubuntu16.04, build_type: Release, developer_mode: OFF }

    container:
      image: ${{ matrix.image }}:latest
      options: "-v ${{ github.workspace }}:${{ github.workspace }} --user=root"

    steps:
      - uses: actions/checkout@v3

      - name: Update CMake
        run: pip install --no-cache-dir 'cmake==3.24.*'

      - name: Generate cache key
        id: cache-key
        run: |
          image="${{ matrix.image }}"
          build_type="${{ matrix.build_type }}"
          hash="${{ hashFiles('conanfile.py', '.github/workflows/unit-tests-ubuntu.yml') }}"

          echo "::set-output name=key::$image-$build_type-$hash"

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: conan-${{ steps.cache-key.outputs.key }}
          path: ${{ env.CONAN_USER_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs

      - name: Install build dependencies
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan install conanfile.py                  \
             --build outdated                         \
             -s build_type="${{ matrix.build_type }}" \
             -s compiler.libcxx=libstdc++11           \
             -s compiler.cppstd=17

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs
          conan remove -f "*" --outdated

      - name: Configure project
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}          \
                -DENABLE_DEVELOPER_MODE=${{ matrix.developer_mode }} \
                -DOPT_ENABLE_CLANG_TIDY=OFF                          \
                -DOPT_ENABLE_CPPCHECK=OFF                            \
                -DENABLE_TESTING=ON                                  \
                -DBUILD_EXAMPLES=ON                                  \
                -S "${{ github.workspace }}"                         \
                -B "${{ github.workspace }}/build"

      - name: Build project
        run: cmake --build ${{ github.workspace }}/build -j $(nproc)

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --test-dir .        \
                --schedule-random   \
                --output-on-failure \
                --no-tests=error    \
                --timeout 120       \
                -j $(nproc)
