# Copyright (C) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Windows CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/windows-ci.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
      - "lsan.supp"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/windows-ci.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
      - "lsan.supp"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  CONAN_V2_MODE: "1"

defaults:
  run:
    shell: bash

jobs:
  build-project:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: conan-${{ hashFiles('conanfile.py', '.github/workflows/windows-ci.yml') }}
          path: ${{ env.CONAN_USER_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug           \
                -DENABLE_DEVELOPER_MODE=OFF        \
                -DCOOLERPP_ENABLE_TESTING=ON       \
                -DCOOLERPP_BUILD_EXAMPLES=ON       \
                -S "${{ github.workspace }}"       \
                -B "${{ github.workspace }}/build"

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs
          conan remove -f "*" --outdated

      - name: Build project
        run: cmake --build ${{ github.workspace }}/build

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --test-dir .        \
                --schedule-random   \
                --output-on-failure \
                --no-tests=error    \
                --timeout 240
